.\" Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.\" Please adjust this date whenever revising the manpage.
.\" 
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.TH "CRYPTKEEPER" "1" "luglio 18, 2007" "Francesco Namuri" ""
.SH "NAME"
cryptkeeper \- EncFS system tray applet for GNOME
.SH "SYNOPSIS"
.B cryptkeeper
.SH "DESCRIPTION"
This manual page documents briefly the
.B cryptkeeper
command
.PP 
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBcryptkeeper\fP is an encrypted folders manager, it allows to mount and umount, to create new folders, to change the password of each mount. It integrates with your preferred file manager.
.SH "OPTIONS"
\fBcryptkeeper\fP doesn't support any command\-line parameter.
.SH "SEE ALSO"
.BR encfs (1).
.SH "AUTHOR"
cryptkeeper was written by Tom Morton <t\-morton@blueyonder.co.uk>.
.PP 
This manual page was written by Francesco Namuri <francesco@namuri.it>,
for the Debian project (but may be used by others).
